// ════════════════════════════════════════════════════════════════════════════
//  MAITRIPOS — GLOBAL THEME ENGINE  v4.0
//  ─────────────────────────────────────────────────────────────────────────
//  HOW TO USE:  Change ONE line — every tenant store auto-updates.
//
//    export const ACTIVE_THEME = "diwali";
//    export const ACTIVE_THEME = "christmas";
//    export const ACTIVE_THEME = "default";   ← clean neutral
//
//  ─────────────────────────────────────────────────────────────────────────
//  VARIABLE REFERENCE (used by PublicStore.jsx + style.css)
//  ─────────────────────────────────────────────────────────────────────────
//
//  accent          → buttons, active tab, search ring, price, tag text,
//                    subcategory border-left, footer link, CTA bg, checkmark
//  accentDark      → hover/press state of accent
//  bg              → full <body> background (gradient or solid)
//                    tip: dark → immersive; light → warm/airy
//  cardBg          → product card + bottom sheet background
//  cardBorder      → card outline, table dividers, tag borders
//  tabActiveBg     → active category pill background
//  tabActiveText   → text ON the active pill (also CTA button text)
//  textPrimary     → headings, names, prices, body copy
//  textSecondary   → muted text, addresses, placeholders, table headers
//  headerBg        → sticky header + sticky tabs surface
//  searchBg        → search bar fill + card image placeholder
//
//  particles       → single emoji rendered as floating page decoration
//                    set null to disable
//  particleCount   → integer 0–20; recommended 8–16
//
//  banner.show     → boolean
//  banner.bg       → gradient/solid for the strip
//  banner.textColor    → line1 colour (headline)
//  banner.subtextColor → line2 colour (subtext)
//  banner.emoji    → decorative emoji beside text
//  banner.line1    → headline  (≤ 38 chars for mobile)
//  banner.line2    → subtext   (≤ 55 chars)
//
//  themeClass      → added as a class on <body> — lets CSS do
//                    per-theme tweaks (border accents, shadows etc.)
//                    values: "theme-light" | "theme-dark"
//
//  font            → reserved for future Google Fonts (null for now)
//
//  ─────────────────────────────────────────────────────────────────────────
//  COMPLETE THEME INDEX
//  ─────────────────────────────────────────────────────────────────────────
//  DEFAULTS          default | dark
//
//  INDIAN            diwali | holi | navratri | dussehra | ganesh_chaturthi
//                    ram_navami | onam | pongal | baisakhi | raksha_bandhan
//                    janmashtami | lohri | makar_sankranti | ugadi | bihu
//                    guru_nanak_jayanti | karva_chauth | durga_puja
//                    maha_shivratri | hanuman_jayanti | gudi_padwa
//                    rath_yatra | nag_panchami | vishu | thrissur_pooram
//                    parsi_new_year
//
//  ISLAMIC           eid_ul_fitr | eid_ul_adha | ramadan | muharram
//                    milad_un_nabi
//
//  CHRISTIAN/WESTERN christmas | easter | good_friday | thanksgiving
//                    halloween | ash_wednesday | pentecost | pancake_day
//
//  GLOBAL SECULAR    new_year | new_year_eve | valentines | mothers_day
//                    fathers_day | womens_day | earth_day | labour_day
//                    childrens_day | independence_day | republic_day | pride
//
//  EAST ASIAN        chinese_new_year | lantern_festival | mid_autumn
//                    japanese_new_year | golden_week | sakura_season
//                    tanabata | songkran | chuseok | seollal | dragon_boat
//                    qixi
//
//  JEWISH            hanukkah | passover | rosh_hashanah | yom_kippur
//                    purim | shavuot
//
//  AFRICAN/CARIBBEAN kwanzaa | carnival_rio | carnival_caribbean
//
//  LATIN AMERICAN    dia_de_muertos | cinco_de_mayo
//
//  EUROPEAN          oktoberfest | bastille_day | st_patricks_day
//                    midsommar | burns_night
//
//  SE ASIAN / OTHER  vesak | nowruz | nauryz | thaipusam | deepavali_sg
//
//  SPORTS            ipl | icc_cricket_world_cup | fifa_world_cup
//                    uefa_euros | olympics | nba_finals | super_bowl
//                    wimbledon | formula1 | isl_football | pro_kabaddi
//                    chess_olympiad | commonwealth_games
//
//  SPECIAL EVENTS    black_friday | cyber_monday | flash_sale
//                    grand_opening | anniversary | back_to_school
//                    summer_vibes | monsoon
// ════════════════════════════════════════════════════════════════════════════

export const ACTIVE_THEME = "ipl"; // ← CHANGE ONLY THIS LINE

export const THEMES = {
  // ══════════════════════════════════════════════════════════════════════
  //  DEFAULTS
  // ══════════════════════════════════════════════════════════════════════

  default: {
    accent: "#111111",
    accentDark: "#333333",
    bg: "#f5f5f5",
    cardBg: "#ffffff",
    cardBorder: "#e8e8e8",
    tabActiveBg: "#111111",
    tabActiveText: "#ffffff",
    textPrimary: "#111111",
    textSecondary: "#888888",
    headerBg: "#ffffff",
    searchBg: "#f0f0f0",
    particles: null,
    particleCount: 0,
    themeClass: "theme-light",
    banner: { show: false },
    font: null,
  },

  dark: {
    accent: "#e0e0e0",
    accentDark: "#bdbdbd",
    bg: "linear-gradient(160deg,#0e0e0e 0%,#1a1a1a 100%)",
    cardBg: "#1e1e1e",
    cardBorder: "#2e2e2e",
    tabActiveBg: "#e0e0e0",
    tabActiveText: "#111111",
    textPrimary: "#f2f2f2",
    textSecondary: "#888888",
    headerBg: "#141414",
    searchBg: "#252525",
    particles: null,
    particleCount: 0,
    themeClass: "theme-dark",
    banner: { show: false },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  INDIAN FESTIVALS
  //
  //  Colour logic:
  //  Diwali   → deep amber/gold on near-black → fire + diyas
  //  Holi     → vivid spectrum banner, magenta accent on deep violet-black
  //  Navratri → dandiya red-orange + deep purple night
  //  Dussehra → saffron flame on deep maroon
  //  Ganesh C → marigold on clean ivory → pooja flowers + prasad
  //  Ram Nav  → warm saffron + ivory → temple morning
  //  Onam     → forest green + gold on white → pookalam flowers
  //  Pongal   → harvest gold on cream → sun + sugarcane
  //  Baisakhi → mustard yellow + deep teal on ivory
  //  Rakhi    → blush pink on white → silk threads + mithai
  //  Janm'mi  → peacock blue + gold on ivory → Krishna
  //  Lohri    → bonfire orange on warm night-sky
  //  Makar S  → sky blue + kite yellow on white
  //  Ugadi    → spring leaf-green on white
  //  Bihu     → earthy red + gold on cream → Assam silk
  //  GNJ      → sacred orange + ivory → Waheguru
  //  KarvaC   → moonrise rose on blush
  //  DurgaP   → vermilion + marigold on warm cream
  //  ShivRatri→ ash-purple + silver on deep ink
  //  Hanuman J→ bright vermilion on cream
  //  GudiP    → festival scarlet + mango yellow on ivory
  //  RathYatra→ chariot gold + temple red on saffron cream
  //  NagPanch → forest + sacred copper on ivory
  //  Vishu    → golden yellow + green on white
  //  ThrissurP→ elephant grey + gold on ivory
  //  ParsiNY  → fire-altar orange on ivory
  // ══════════════════════════════════════════════════════════════════════

  diwali: {
    // Deep amber on near-black — oil lamps, gold rangoli
    accent: "#f5a623",
    accentDark: "#d4881a",
    bg: "linear-gradient(160deg,#0d0400 0%,#1f0a00 45%,#090200 100%)",
    cardBg: "#1c0900",
    cardBorder: "#3d1c00",
    tabActiveBg: "#f5a623",
    tabActiveText: "#1c0900",
    textPrimary: "#fff8e1",
    textSecondary: "#c8a26a",
    headerBg: "#140600",
    searchBg: "#2a1200",
    particles: "🪔",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#2d1000,#5c2800,#2d1000)",
      textColor: "#ffd700",
      subtextColor: "#f5a623",
      emoji: "🪔",
      line1: "Shubh Deepawali! ✨",
      line2: "Celebrate the festival of lights with our specials",
    },
    font: null,
  },

  holi: {
    // Vivid spectrum — powder colours fill the air
    accent: "#ff0080",
    accentDark: "#d10069",
    bg: "linear-gradient(150deg,#18001a 0%,#0a0830 50%,#001810 100%)",
    cardBg: "#160012",
    cardBorder: "#3d0035",
    tabActiveBg: "#ff0080",
    tabActiveText: "#ffffff",
    textPrimary: "#fff0fa",
    textSecondary: "#e0a0cc",
    headerBg: "#0e000e",
    searchBg: "#20001a",
    particles: "🎨",
    particleCount: 18,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#c0392b,#e67e22,#8e44ad,#27ae60,#2980b9)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.92)",
      emoji: "🌈",
      line1: "Happy Holi! Rang Barse 🌈",
      line2: "Colour your world with our freshest picks",
    },
    font: null,
  },

  navratri: {
    // Crimson + saffron on deep ink-purple — garba night
    accent: "#ff6200",
    accentDark: "#e05500",
    bg: "linear-gradient(160deg,#16001e 0%,#280040 55%,#16001e 100%)",
    cardBg: "#1e0028",
    cardBorder: "#500060",
    tabActiveBg: "#ff6200",
    tabActiveText: "#ffffff",
    textPrimary: "#ffe8ff",
    textSecondary: "#cc88cc",
    headerBg: "#14001a",
    searchBg: "#280030",
    particles: "💃",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#5a0080,#c0006a,#ff6200,#c0006a,#5a0080)",
      textColor: "#ffffff",
      subtextColor: "#f5d0ff",
      emoji: "🪷",
      line1: "Jai Mata Di! Shubh Navratri 🎶",
      line2: "Nine nights of devotion, dance & festive treats",
    },
    font: null,
  },

  dussehra: {
    // Saffron flame + gold on maroon-black — Ravan dahan
    accent: "#ff7300",
    accentDark: "#e06200",
    bg: "linear-gradient(160deg,#1c0000 0%,#300a00 55%,#1c0000 100%)",
    cardBg: "#220500",
    cardBorder: "#601500",
    tabActiveBg: "#ff7300",
    tabActiveText: "#ffffff",
    textPrimary: "#fff4e6",
    textSecondary: "#cc9966",
    headerBg: "#1a0200",
    searchBg: "#300900",
    particles: "🏹",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800000,#cc3300,#ff7300,#cc3300,#800000)",
      textColor: "#ffd700",
      subtextColor: "#ffbb55",
      emoji: "🏹",
      line1: "Happy Dussehra! Vijaya Dashami 🔥",
      line2: "Celebrating the victory of good over evil",
    },
    font: null,
  },

  ganesh_chaturthi: {
    // Marigold orange + ivory white — temple flowers + modak
    accent: "#e65c00",
    accentDark: "#bf4d00",
    bg: "#fff8f0",
    cardBg: "#ffffff",
    cardBorder: "#ffe0c0",
    tabActiveBg: "#e65c00",
    tabActiveText: "#ffffff",
    textPrimary: "#3e2000",
    textSecondary: "#7d4c00",
    headerBg: "#ffffff",
    searchBg: "#fff3e5",
    particles: "🐘",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#8b2500,#e65c00,#ffb300,#e65c00,#8b2500)",
      textColor: "#ffffff",
      subtextColor: "#fff0d0",
      emoji: "🐘",
      line1: "Ganpati Bappa Morya! 🙏",
      line2: "Divine sweets for the most beloved arrival",
    },
    font: null,
  },

  ram_navami: {
    // Sacred saffron + ivory morning — temple dawn
    accent: "#d45500",
    accentDark: "#b34600",
    bg: "#fffaf0",
    cardBg: "#ffffff",
    cardBorder: "#ffd9a8",
    tabActiveBg: "#d45500",
    tabActiveText: "#ffffff",
    textPrimary: "#3a1800",
    textSecondary: "#7a4000",
    headerBg: "#ffffff",
    searchBg: "#fff4e0",
    particles: "🪷",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#8b1a00,#d45500,#ff9a00,#d45500,#8b1a00)",
      textColor: "#ffffff",
      subtextColor: "#ffe8b0",
      emoji: "🙏",
      line1: "Jai Shri Ram! Happy Ram Navami 🪷",
      line2: "Celebrating the birth of Lord Ram — blessings to all",
    },
    font: null,
  },

  onam: {
    // Deep forest green + festival gold — pookalam + sadya
    accent: "#2a7d2e",
    accentDark: "#1b5e20",
    bg: "#f0faf0",
    cardBg: "#ffffff",
    cardBorder: "#b8dfba",
    tabActiveBg: "#2a7d2e",
    tabActiveText: "#ffffff",
    textPrimary: "#0d2e10",
    textSecondary: "#3a7040",
    headerBg: "#ffffff",
    searchBg: "#e8f8e8",
    particles: "🌸",
    particleCount: 14,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2a7d2e,#f9a825,#2a7d2e,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#fff9c4",
      emoji: "🌼",
      line1: "Onam Ashamsakal! Happy Onam 🌼",
      line2: "Harvest joy with our special Kerala treats",
    },
    font: null,
  },

  pongal: {
    // Harvest gold + sugarcane cream — kolam + sun worship
    accent: "#c77d00",
    accentDark: "#a06500",
    bg: "#fffcf0",
    cardBg: "#ffffff",
    cardBorder: "#ffe4a0",
    tabActiveBg: "#c77d00",
    tabActiveText: "#ffffff",
    textPrimary: "#3a2800",
    textSecondary: "#7a5500",
    headerBg: "#ffffff",
    searchBg: "#fff9e5",
    particles: "🌾",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a4000,#c77d00,#f9d74f,#c77d00,#7a4000)",
      textColor: "#ffffff",
      subtextColor: "#fffce0",
      emoji: "🌾",
      line1: "Pongal-o-Pongal! Happy Pongal 🌞",
      line2: "Celebrate the harvest with our traditional sweets",
    },
    font: null,
  },

  baisakhi: {
    // Mustard + teal on warm ivory — Punjab fields
    accent: "#d17a00",
    accentDark: "#b06500",
    bg: "#fffde5",
    cardBg: "#ffffff",
    cardBorder: "#ffe590",
    tabActiveBg: "#d17a00",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1a00",
    textSecondary: "#6e4400",
    headerBg: "#ffffff",
    searchBg: "#fffbe0",
    particles: "🌾",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#5a3000,#d17a00,#f9e040,#d17a00,#5a3000)",
      textColor: "#ffffff",
      subtextColor: "#fffde0",
      emoji: "🎉",
      line1: "Vaisakhi Mubarak! 🌾",
      line2: "New harvest, new year, new celebrations",
    },
    font: null,
  },

  raksha_bandhan: {
    // Rose-blush + gold thread on pure white — silk rakhi
    accent: "#c0185a",
    accentDark: "#960e46",
    bg: "#fff5f8",
    cardBg: "#ffffff",
    cardBorder: "#ffc0d0",
    tabActiveBg: "#c0185a",
    tabActiveText: "#ffffff",
    textPrimary: "#500018",
    textSecondary: "#a0305a",
    headerBg: "#ffffff",
    searchBg: "#ffeef3",
    particles: "🪢",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800030,#c0185a,#ff80a0,#c0185a,#800030)",
      textColor: "#ffffff",
      subtextColor: "#fde8ee",
      emoji: "🎁",
      line1: "Happy Raksha Bandhan! 💕",
      line2: "Sweeten the bond of love with our mithai",
    },
    font: null,
  },

  janmashtami: {
    // Peacock blue-teal + gold on white — Krishna's colours
    accent: "#1055a0",
    accentDark: "#0a3e80",
    bg: "#f0f6ff",
    cardBg: "#ffffff",
    cardBorder: "#b8d0f0",
    tabActiveBg: "#1055a0",
    tabActiveText: "#ffffff",
    textPrimary: "#071a40",
    textSecondary: "#2a5088",
    headerBg: "#ffffff",
    searchBg: "#e8f0fc",
    particles: "🦚",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#072a60,#1055a0,#ffd700,#1055a0,#072a60)",
      textColor: "#ffffff",
      subtextColor: "#ffe070",
      emoji: "🦚",
      line1: "Jai Shri Krishna! Happy Janmashtami 🙏",
      line2: "Celebrate with our handmade mithai & festive specials",
    },
    font: null,
  },

  lohri: {
    // Bonfire deep-orange on warm night — sparks fly
    accent: "#ff5a00",
    accentDark: "#d44a00",
    bg: "linear-gradient(160deg,#1a0500 0%,#2e1000 50%,#1a0500 100%)",
    cardBg: "#220800",
    cardBorder: "#601800",
    tabActiveBg: "#ff5a00",
    tabActiveText: "#ffffff",
    textPrimary: "#fff5e5",
    textSecondary: "#cc8855",
    headerBg: "#1a0500",
    searchBg: "#2e0e00",
    particles: "🔥",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a1500,#cc3500,#ff5a00,#ffc200,#ff5a00,#cc3500,#7a1500)",
      textColor: "#ffffff",
      subtextColor: "#ffe0b0",
      emoji: "🔥",
      line1: "Happy Lohri! 🌾",
      line2: "Warmth, bonfire & festive bites",
    },
    font: null,
  },

  makar_sankranti: {
    // Sky blue + kite yellow on white — Uttarayan sky
    accent: "#0288c4",
    accentDark: "#01639a",
    bg: "#f0faff",
    cardBg: "#ffffff",
    cardBorder: "#b0dcf0",
    tabActiveBg: "#0288c4",
    tabActiveText: "#ffffff",
    textPrimary: "#012840",
    textSecondary: "#0560a0",
    headerBg: "#ffffff",
    searchBg: "#e5f5ff",
    particles: "🪁",
    particleCount: 14,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#01579b,#0288c4,#f9c825,#0288c4,#01579b)",
      textColor: "#ffffff",
      subtextColor: "#fff9c4",
      emoji: "🪁",
      line1: "Happy Makar Sankranti! 🌤️",
      line2: "Flying high with til-gur and tradition",
    },
    font: null,
  },

  ugadi: {
    // Fresh spring green on white — Kanakambaram + raw mango
    accent: "#2e7d32",
    accentDark: "#1b5e20",
    bg: "#f5faf5",
    cardBg: "#ffffff",
    cardBorder: "#b8ddb8",
    tabActiveBg: "#2e7d32",
    tabActiveText: "#ffffff",
    textPrimary: "#0d2e10",
    textSecondary: "#3a7040",
    headerBg: "#ffffff",
    searchBg: "#ecf8ec",
    particles: "🌿",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2e7d32,#f9c825,#2e7d32,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#fff9c4",
      emoji: "🌿",
      line1: "Happy Ugadi! Telugu & Kannada New Year 🌸",
      line2: "Sweet, sour, bitter — a year full of flavours",
    },
    font: null,
  },

  bihu: {
    // Muga-silk red + harvest gold on cream — Assam
    accent: "#c0200e",
    accentDark: "#9a1808",
    bg: "#fff9f0",
    cardBg: "#ffffff",
    cardBorder: "#ffd5b0",
    tabActiveBg: "#c0200e",
    tabActiveText: "#ffffff",
    textPrimary: "#3a1000",
    textSecondary: "#8a3010",
    headerBg: "#ffffff",
    searchBg: "#fff4e8",
    particles: "🎶",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a0c00,#c0200e,#f9a825,#c0200e,#7a0c00)",
      textColor: "#ffffff",
      subtextColor: "#ffe8b0",
      emoji: "🌾",
      line1: "Subho Bihu! Happy Rongali Bihu 🌾",
      line2: "Celebrating the vibrant spirit of Assam",
    },
    font: null,
  },

  guru_nanak_jayanti: {
    // Sacred orange + ivory — Waheguru light
    accent: "#d07800",
    accentDark: "#a86000",
    bg: "#fffcf0",
    cardBg: "#ffffff",
    cardBorder: "#ffe8a0",
    tabActiveBg: "#d07800",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1a00",
    textSecondary: "#6e4400",
    headerBg: "#ffffff",
    searchBg: "#fffae5",
    particles: "☀️",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#5a3000,#d07800,#f9d040,#d07800,#5a3000)",
      textColor: "#ffffff",
      subtextColor: "#fff9d0",
      emoji: "🙏",
      line1: "Gurpurab Mubarak! Waheguru Ji 🙏",
      line2: "Truth, service and community — always",
    },
    font: null,
  },

  karva_chauth: {
    // Moonrise rose-magenta on blush — chandni raat
    accent: "#b81650",
    accentDark: "#900e3e",
    bg: "#fff2f6",
    cardBg: "#ffffff",
    cardBorder: "#ffb8cc",
    tabActiveBg: "#b81650",
    tabActiveText: "#ffffff",
    textPrimary: "#450018",
    textSecondary: "#980040",
    headerBg: "#ffffff",
    searchBg: "#ffeaf0",
    particles: "🌙",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#780030,#b81650,#ff80a8,#b81650,#780030)",
      textColor: "#ffffff",
      subtextColor: "#fde8ee",
      emoji: "🌙",
      line1: "Happy Karva Chauth! 💕",
      line2: "Celebrating love, moonlight & devotion",
    },
    font: null,
  },

  durga_puja: {
    // Sindoor vermilion + marigold on warm cream — Maa Durga
    accent: "#b71818",
    accentDark: "#8c0f0f",
    bg: "#fffdf0",
    cardBg: "#ffffff",
    cardBorder: "#ffe0a0",
    tabActiveBg: "#b71818",
    tabActiveText: "#ffffff",
    textPrimary: "#2e0e00",
    textSecondary: "#7a3000",
    headerBg: "#ffffff",
    searchBg: "#fff9e8",
    particles: "🌺",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#700000,#b71818,#f9a825,#b71818,#700000)",
      textColor: "#ffffff",
      subtextColor: "#ffe8a0",
      emoji: "🌺",
      line1: "Shubh Durga Puja! Subho Bijoya 🙏",
      line2: "Celebrating the triumph of the divine mother",
    },
    font: null,
  },

  maha_shivratri: {
    // Deep violet + silver ash on near-black — bhasma, trishul
    accent: "#7c3aed",
    accentDark: "#6020c8",
    bg: "linear-gradient(160deg,#0a0014 0%,#14002a 55%,#0a0014 100%)",
    cardBg: "#100020",
    cardBorder: "#380060",
    tabActiveBg: "#7c3aed",
    tabActiveText: "#ffffff",
    textPrimary: "#f0e8ff",
    textSecondary: "#b088e0",
    headerBg: "#0a0014",
    searchBg: "#1c0030",
    particles: "🔱",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1e0044,#5a1a99,#7c3aed,#5a1a99,#1e0044)",
      textColor: "#e0c8ff",
      subtextColor: "#c8a8f0",
      emoji: "🔱",
      line1: "Har Har Mahadev! Happy Maha Shivratri 🙏",
      line2: "Sacred night of Lord Shiva — blessings to all",
    },
    font: null,
  },

  hanuman_jayanti: {
    // Bright vermilion on ivory + pure white — Bajrangbali
    accent: "#c82800",
    accentDark: "#a02000",
    bg: "#fff8f5",
    cardBg: "#ffffff",
    cardBorder: "#ffc8b0",
    tabActiveBg: "#c82800",
    tabActiveText: "#ffffff",
    textPrimary: "#3a0800",
    textSecondary: "#8a2800",
    headerBg: "#ffffff",
    searchBg: "#fff3ee",
    particles: "🪄",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a1000,#c82800,#ff6800,#c82800,#7a1000)",
      textColor: "#ffffff",
      subtextColor: "#ffe0c8",
      emoji: "🐒",
      line1: "Jai Bajrangbali! Happy Hanuman Jayanti 🙏",
      line2: "Strength, devotion & blessings to all",
    },
    font: null,
  },

  gudi_padwa: {
    // Festive scarlet + mango yellow on ivory — new year flag
    accent: "#cc3000",
    accentDark: "#a02500",
    bg: "#fffcf0",
    cardBg: "#ffffff",
    cardBorder: "#ffe0a0",
    tabActiveBg: "#cc3000",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1000",
    textSecondary: "#7a3800",
    headerBg: "#ffffff",
    searchBg: "#fff9e8",
    particles: "🚩",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a1800,#cc3000,#f9c000,#cc3000,#7a1800)",
      textColor: "#ffffff",
      subtextColor: "#ffe8b0",
      emoji: "🚩",
      line1: "Gudi Padwa Chya Shubhechha! 🌿",
      line2: "Marathi New Year — new beginnings & blessings",
    },
    font: null,
  },

  rath_yatra: {
    // Chariot gold + temple red on saffron cream
    accent: "#c87000",
    accentDark: "#a05800",
    bg: "#fff9e8",
    cardBg: "#ffffff",
    cardBorder: "#ffe4a0",
    tabActiveBg: "#c87000",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1800",
    textSecondary: "#7a4000",
    headerBg: "#ffffff",
    searchBg: "#fff5d8",
    particles: "🎡",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a3000,#c87000,#f9d000,#c87000,#7a3000)",
      textColor: "#ffffff",
      subtextColor: "#ffe8a0",
      emoji: "🛕",
      line1: "Jai Jagannath! Happy Rath Yatra 🎡",
      line2: "The grand chariot festival — divine blessings",
    },
    font: null,
  },

  nag_panchami: {
    // Forest + sacred copper on ivory — nag devata
    accent: "#2a7d32",
    accentDark: "#1b5e20",
    bg: "#f5faf5",
    cardBg: "#ffffff",
    cardBorder: "#b8ddb8",
    tabActiveBg: "#2a7d32",
    tabActiveText: "#ffffff",
    textPrimary: "#0d2e10",
    textSecondary: "#3a7040",
    headerBg: "#ffffff",
    searchBg: "#ecf8ec",
    particles: "🌿",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2a7d32,#c87000,#2a7d32,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#e8f5e9",
      emoji: "🐍",
      line1: "Happy Nag Panchami! 🙏",
      line2: "Worship of the divine serpent — blessings to all",
    },
    font: null,
  },

  vishu: {
    // Kanikkonna gold on white + Kerala green — vishukkani
    accent: "#c8a200",
    accentDark: "#a08000",
    bg: "#fffff0",
    cardBg: "#ffffff",
    cardBorder: "#f0e890",
    tabActiveBg: "#c8a200",
    tabActiveText: "#ffffff",
    textPrimary: "#2a2000",
    textSecondary: "#706000",
    headerBg: "#ffffff",
    searchBg: "#ffffe8",
    particles: "🌼",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2a7d32,#c8a200,#2a7d32,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#fffce0",
      emoji: "🌼",
      line1: "Vishu Aashamsagal! Happy Vishu 🎆",
      line2: "Kerala New Year — prosperity & joy",
    },
    font: null,
  },

  thrissur_pooram: {
    // Caparisoned elephant grey + festival gold + ivory
    accent: "#c87800",
    accentDark: "#a06000",
    bg: "#fffcf0",
    cardBg: "#ffffff",
    cardBorder: "#ffe8a0",
    tabActiveBg: "#c87800",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1800",
    textSecondary: "#7a4400",
    headerBg: "#ffffff",
    searchBg: "#fff9e5",
    particles: "🐘",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a3800,#c87800,#f9d040,#c87800,#7a3800)",
      textColor: "#ffffff",
      subtextColor: "#ffe8a0",
      emoji: "🐘",
      line1: "Thrissur Pooram! Kerala's grandest festival 🎆",
      line2: "The spectacular elephant procession — a sight to behold",
    },
    font: null,
  },

  parsi_new_year: {
    // Fire-altar orange + ivory — Zoroastrian Nowruz
    accent: "#d06800",
    accentDark: "#a85200",
    bg: "#fffcf0",
    cardBg: "#ffffff",
    cardBorder: "#ffe8b0",
    tabActiveBg: "#d06800",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1800",
    textSecondary: "#7a4000",
    headerBg: "#ffffff",
    searchBg: "#fff9e8",
    particles: "🔥",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a2800,#d06800,#f9d040,#d06800,#7a2800)",
      textColor: "#ffffff",
      subtextColor: "#ffe8b0",
      emoji: "🔥",
      line1: "Navroz Mubarak! Happy Parsi New Year 🎊",
      line2: "Celebrating the Zoroastrian New Year in joy",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  ISLAMIC FESTIVALS
  //  Eid      → deep teal-green + gold (crescent colours)
  //  Ramadan  → midnight indigo + crescent gold
  //  Muharram → restrained charcoal (solemn)
  //  Milad    → sacred forest green + gold
  // ══════════════════════════════════════════════════════════════════════

  eid_ul_fitr: {
    accent: "#00796b",
    accentDark: "#00574a",
    bg: "linear-gradient(160deg,#001a14 0%,#002e22 55%,#001a14 100%)",
    cardBg: "#001e18",
    cardBorder: "#004030",
    tabActiveBg: "#00796b",
    tabActiveText: "#ffffff",
    textPrimary: "#d8fff8",
    textSecondary: "#70b8a8",
    headerBg: "#001610",
    searchBg: "#002820",
    particles: "🌙",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#004838,#00796b,#c9a030,#00796b,#004838)",
      textColor: "#c9d890",
      subtextColor: "#a0c880",
      emoji: "🌙",
      line1: "Eid Mubarak! عيد مبارك ⭐",
      line2: "Celebrate the end of Ramadan with joy & sweets",
    },
    font: null,
  },

  eid_ul_adha: {
    accent: "#006858",
    accentDark: "#005040",
    bg: "linear-gradient(160deg,#001810 0%,#002a1c 55%,#001810 100%)",
    cardBg: "#001c14",
    cardBorder: "#003828",
    tabActiveBg: "#006858",
    tabActiveText: "#ffffff",
    textPrimary: "#d0fff4",
    textSecondary: "#60b0a0",
    headerBg: "#00140c",
    searchBg: "#00221a",
    particles: "⭐",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#004030,#006858,#c9a030,#006858,#004030)",
      textColor: "#c8d880",
      subtextColor: "#a0c870",
      emoji: "☪️",
      line1: "Eid ul Adha Mubarak! عيد الأضحى مبارك",
      line2: "Festival of sacrifice — celebrate with our items",
    },
    font: null,
  },

  ramadan: {
    // Midnight indigo + crescent gold — laylat al-qadr
    accent: "#6060c8",
    accentDark: "#4848a8",
    bg: "linear-gradient(160deg,#06001e 0%,#0c0038 55%,#06001e 100%)",
    cardBg: "#080024",
    cardBorder: "#20005a",
    tabActiveBg: "#6060c8",
    tabActiveText: "#ffffff",
    textPrimary: "#e8e6ff",
    textSecondary: "#9090cc",
    headerBg: "#050018",
    searchBg: "#0c0030",
    particles: "🌙",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#100040,#2e0080,#6060c8,#2e0080,#100040)",
      textColor: "#c0d0ff",
      subtextColor: "#a0b8f0",
      emoji: "🌙",
      line1: "Ramadan Kareem! رمضان كريم ✨",
      line2: "A blessed month of fasting, prayer & reflection",
    },
    font: null,
  },

  muharram: {
    // Charcoal + slate — solemn
    accent: "#607080",
    accentDark: "#485860",
    bg: "linear-gradient(160deg,#080a0c 0%,#0e1214 100%)",
    cardBg: "#0c1014",
    cardBorder: "#202830",
    tabActiveBg: "#607080",
    tabActiveText: "#ffffff",
    textPrimary: "#d8e0e8",
    textSecondary: "#6a7880",
    headerBg: "#0a0c10",
    searchBg: "#14181e",
    particles: null,
    particleCount: 0,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0e1214,#202830,#0e1214)",
      textColor: "#c0c8d0",
      subtextColor: "#909aa0",
      emoji: "☪️",
      line1: "Muharram — Islamic New Year",
      line2: "A time of reflection, remembrance & renewal",
    },
    font: null,
  },

  milad_un_nabi: {
    // Sacred green + gold — Prophet's birthday
    accent: "#2e7d32",
    accentDark: "#1b5e20",
    bg: "linear-gradient(160deg,#001c00 0%,#003000 55%,#001c00 100%)",
    cardBg: "#001800",
    cardBorder: "#004800",
    tabActiveBg: "#2e7d32",
    tabActiveText: "#ffffff",
    textPrimary: "#d8ffd8",
    textSecondary: "#70b870",
    headerBg: "#001400",
    searchBg: "#002400",
    particles: "🌟",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2e7d32,#c9a030,#2e7d32,#1b5e20)",
      textColor: "#c8e890",
      subtextColor: "#a0c870",
      emoji: "🌟",
      line1: "Mawlid al-Nabi Mubarak! مولد النبي",
      line2: "Celebrating the birth of the Prophet ﷺ",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  CHRISTIAN / WESTERN
  //  Christmas → forest green + red on deep spruce
  //  Easter    → lavender + pastel on white
  //  Good Fri  → charcoal brown (solemn)
  //  Thanksgi  → burnt sienna + harvest cream
  //  Halloween → pumpkin orange on near-black purple
  // ══════════════════════════════════════════════════════════════════════

  christmas: {
    // Forest green + cardinal red on deep spruce night
    accent: "#d42828",
    accentDark: "#a81e1e",
    bg: "linear-gradient(160deg,#001a00 0%,#003000 50%,#001a00 100%)",
    cardBg: "#002000",
    cardBorder: "#005000",
    tabActiveBg: "#d42828",
    tabActiveText: "#ffffff",
    textPrimary: "#e8ffe8",
    textSecondary: "#80c880",
    headerBg: "#001800",
    searchBg: "#002a00",
    particles: "❄️",
    particleCount: 18,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1a5e20,#2e8e38,#d42828,#2e8e38,#1a5e20)",
      textColor: "#ffd700",
      subtextColor: "#a8e888",
      emoji: "🎄",
      line1: "Merry Christmas! 🎁",
      line2: "Festive treats for the season of joy",
    },
    font: null,
  },

  easter: {
    // Lavender + pastel spectrum on pure white
    accent: "#7b1fa2",
    accentDark: "#5e1780",
    bg: "#f8f0ff",
    cardBg: "#ffffff",
    cardBorder: "#e0c8f0",
    tabActiveBg: "#7b1fa2",
    tabActiveText: "#ffffff",
    textPrimary: "#2a0840",
    textSecondary: "#6a3090",
    headerBg: "#ffffff",
    searchBg: "#f5eaff",
    particles: "🐣",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#5e1780,#9c27b0,#ce93d8,#9c27b0,#5e1780)",
      textColor: "#ffffff",
      subtextColor: "#f0e0ff",
      emoji: "🐣",
      line1: "Happy Easter! He is Risen 🌸",
      line2: "Sweet treats for a beautiful celebration",
    },
    font: null,
  },

  good_friday: {
    // Deep umber + parchment — solemn
    accent: "#5a3828",
    accentDark: "#402818",
    bg: "linear-gradient(160deg,#080402 0%,#100a06 100%)",
    cardBg: "#100604",
    cardBorder: "#302010",
    tabActiveBg: "#5a3828",
    tabActiveText: "#ffffff",
    textPrimary: "#f0e0d0",
    textSecondary: "#a08870",
    headerBg: "#0c0604",
    searchBg: "#181008",
    particles: null,
    particleCount: 0,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#181008,#3a2010,#181008)",
      textColor: "#d0c0b0",
      subtextColor: "#b0a090",
      emoji: "✝️",
      line1: "Good Friday — A Day of Reflection",
      line2: "We honour this sacred day with you",
    },
    font: null,
  },

  thanksgiving: {
    // Burnt sienna + harvest cream — autumn leaves
    accent: "#c04800",
    accentDark: "#9a3800",
    bg: "#fff6ed",
    cardBg: "#ffffff",
    cardBorder: "#ffd8a8",
    tabActiveBg: "#c04800",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1000",
    textSecondary: "#7a4000",
    headerBg: "#ffffff",
    searchBg: "#fff2e5",
    particles: "🍂",
    particleCount: 14,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a2800,#c04800,#f9a825,#c04800,#7a2800)",
      textColor: "#ffffff",
      subtextColor: "#ffe8c0",
      emoji: "🦃",
      line1: "Happy Thanksgiving! 🍂",
      line2: "Grateful for every bite — our harvest specials",
    },
    font: null,
  },

  halloween: {
    // Pumpkin orange on near-black + dark purple
    accent: "#e06000",
    accentDark: "#b84e00",
    bg: "linear-gradient(160deg,#080008 0%,#100018 55%,#080008 100%)",
    cardBg: "#0c000c",
    cardBorder: "#400048",
    tabActiveBg: "#e06000",
    tabActiveText: "#0c000c",
    textPrimary: "#ffe8d0",
    textSecondary: "#aa7090",
    headerBg: "#0a0008",
    searchBg: "#180014",
    particles: "🎃",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#200028,#500058,#e06000,#500058,#200028)",
      textColor: "#e06000",
      subtextColor: "#ffcca0",
      emoji: "🎃",
      line1: "Happy Halloween! 👻",
      line2: "Trick or treat — find something deliciously spooky",
    },
    font: null,
  },

  ash_wednesday: {
    accent: "#788090",
    accentDark: "#586070",
    bg: "linear-gradient(160deg,#0c0c0e 0%,#141618 100%)",
    cardBg: "#101214",
    cardBorder: "#282c30",
    tabActiveBg: "#788090",
    tabActiveText: "#ffffff",
    textPrimary: "#d8dce0",
    textSecondary: "#788090",
    headerBg: "#0c0e10",
    searchBg: "#181c20",
    particles: null,
    particleCount: 0,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#141618,#282c30,#141618)",
      textColor: "#c0c8d0",
      subtextColor: "#909aa0",
      emoji: "✝️",
      line1: "Ash Wednesday — Beginning of Lent",
      line2: "A season of reflection & renewal begins",
    },
    font: null,
  },

  pentecost: {
    // Flame red + dove white on deep scarlet
    accent: "#e03030",
    accentDark: "#b82020",
    bg: "linear-gradient(160deg,#200000 0%,#380010 50%,#200000 100%)",
    cardBg: "#280008",
    cardBorder: "#600020",
    tabActiveBg: "#e03030",
    tabActiveText: "#ffffff",
    textPrimary: "#fff0f0",
    textSecondary: "#cc8888",
    headerBg: "#200006",
    searchBg: "#300010",
    particles: "🕊️",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800000,#e03030,#ff8888,#e03030,#800000)",
      textColor: "#ffffff",
      subtextColor: "#ffc8c8",
      emoji: "🕊️",
      line1: "Happy Pentecost! Come, Holy Spirit 🔥",
      line2: "Celebrating the descent of the Holy Spirit",
    },
    font: null,
  },

  pancake_day: {
    // Golden pancake brown + lemon on warm cream
    accent: "#c07800",
    accentDark: "#9a6000",
    bg: "#fff8f0",
    cardBg: "#ffffff",
    cardBorder: "#ffd8a8",
    tabActiveBg: "#c07800",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1800",
    textSecondary: "#7a4400",
    headerBg: "#ffffff",
    searchBg: "#fff4e5",
    particles: "🥞",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a3800,#c07800,#f9d040,#c07800,#7a3800)",
      textColor: "#ffffff",
      subtextColor: "#ffe8c0",
      emoji: "🥞",
      line1: "Happy Pancake Day! Shrove Tuesday 🍋",
      line2: "Flip your best — sweet toppings & good times",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  GLOBAL SECULAR
  // ══════════════════════════════════════════════════════════════════════

  new_year: {
    // Deep midnight navy + champagne gold — fireworks
    accent: "#d4a800",
    accentDark: "#a88400",
    bg: "linear-gradient(160deg,#030214 0%,#060630 55%,#030214 100%)",
    cardBg: "#050520",
    cardBorder: "#201868",
    tabActiveBg: "#d4a800",
    tabActiveText: "#050520",
    textPrimary: "#e8eaff",
    textSecondary: "#7888cc",
    headerBg: "#040318",
    searchBg: "#0a0a30",
    particles: "🎆",
    particleCount: 16,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#060630,#1a1a88,#d4a800,#1a1a88,#060630)",
      textColor: "#d4a800",
      subtextColor: "#f0e060",
      emoji: "🎆",
      line1: "Happy New Year! 🥂",
      line2: "Welcome the year with our very best",
    },
    font: null,
  },

  new_year_eve: {
    // Deep purple-black + electric violet — countdown
    accent: "#cc40ff",
    accentDark: "#aa20e0",
    bg: "linear-gradient(160deg,#060010 0%,#0e0030 55%,#060010 100%)",
    cardBg: "#0a0020",
    cardBorder: "#280068",
    tabActiveBg: "#cc40ff",
    tabActiveText: "#0a0020",
    textPrimary: "#f0e8ff",
    textSecondary: "#a880cc",
    headerBg: "#08001a",
    searchBg: "#140030",
    particles: "🎇",
    particleCount: 18,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#100038,#4a0090,#cc40ff,#4a0090,#100038)",
      textColor: "#e8b0ff",
      subtextColor: "#cc80f0",
      emoji: "🎇",
      line1: "New Year's Eve! 🕛 Countdown begins",
      line2: "The biggest night of the year — celebrate in style",
    },
    font: null,
  },

  valentines: {
    // Crimson rose on blush — love & romance
    accent: "#d01860",
    accentDark: "#a81248",
    bg: "#fff2f6",
    cardBg: "#ffffff",
    cardBorder: "#ffbad0",
    tabActiveBg: "#d01860",
    tabActiveText: "#ffffff",
    textPrimary: "#480018",
    textSecondary: "#a03060",
    headerBg: "#ffffff",
    searchBg: "#ffecf2",
    particles: "💝",
    particleCount: 14,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800030,#d01860,#ff80b0,#d01860,#800030)",
      textColor: "#ffffff",
      subtextColor: "#fde8ee",
      emoji: "💝",
      line1: "Happy Valentine's Day! 💕",
      line2: "Share something sweet with someone you love",
    },
    font: null,
  },

  mothers_day: {
    // Warm rose + peach on white — bouquet of love
    accent: "#d04070",
    accentDark: "#a83055",
    bg: "#fff5f8",
    cardBg: "#ffffff",
    cardBorder: "#ffc8da",
    tabActiveBg: "#d04070",
    tabActiveText: "#ffffff",
    textPrimary: "#480018",
    textSecondary: "#a03060",
    headerBg: "#ffffff",
    searchBg: "#ffeef4",
    particles: "💐",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800030,#d04070,#ffa0b8,#d04070,#800030)",
      textColor: "#ffffff",
      subtextColor: "#fde8ee",
      emoji: "💐",
      line1: "Happy Mother's Day! 🌸",
      line2: "Treat the most important person in your life",
    },
    font: null,
  },

  fathers_day: {
    // Steel blue + amber on white — strength & warmth
    accent: "#1050a0",
    accentDark: "#0a3a80",
    bg: "#f0f6ff",
    cardBg: "#ffffff",
    cardBorder: "#b0c8f0",
    tabActiveBg: "#1050a0",
    tabActiveText: "#ffffff",
    textPrimary: "#071830",
    textSecondary: "#284888",
    headerBg: "#ffffff",
    searchBg: "#e8f0fc",
    particles: "👔",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#072a60,#1050a0,#4898e0,#1050a0,#072a60)",
      textColor: "#ffffff",
      subtextColor: "#c8e0ff",
      emoji: "👔",
      line1: "Happy Father's Day! 🎉",
      line2: "Give him something delicious — he deserves it",
    },
    font: null,
  },

  womens_day: {
    // Purple + gold on white — strength & dignity
    accent: "#8020a0",
    accentDark: "#601880",
    bg: "#faf0ff",
    cardBg: "#ffffff",
    cardBorder: "#e0b8f0",
    tabActiveBg: "#8020a0",
    tabActiveText: "#ffffff",
    textPrimary: "#280040",
    textSecondary: "#7030a0",
    headerBg: "#ffffff",
    searchBg: "#f5e8ff",
    particles: "💜",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#4a1070,#8020a0,#d070d0,#8020a0,#4a1070)",
      textColor: "#ffffff",
      subtextColor: "#f0d8ff",
      emoji: "💜",
      line1: "Happy International Women's Day! 🌸",
      line2: "Celebrating the strength & grace of women everywhere",
    },
    font: null,
  },

  earth_day: {
    // Earth blue + forest green on white
    accent: "#1e6e28",
    accentDark: "#145220",
    bg: "#f0fbf0",
    cardBg: "#ffffff",
    cardBorder: "#a8d8a8",
    tabActiveBg: "#1e6e28",
    tabActiveText: "#ffffff",
    textPrimary: "#0a2810",
    textSecondary: "#287838",
    headerBg: "#ffffff",
    searchBg: "#e8f8e8",
    particles: "🌍",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#1e6e28,#1565c0,#1e6e28,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#c8eec8",
      emoji: "🌍",
      line1: "Happy Earth Day! 🌱",
      line2: "One planet — celebrate it sustainably",
    },
    font: null,
  },

  labour_day: {
    // Union red + gold on near-black — workers' rights
    accent: "#cc2020",
    accentDark: "#a01818",
    bg: "linear-gradient(160deg,#0e0000 0%,#1e0000 100%)",
    cardBg: "#160000",
    cardBorder: "#480000",
    tabActiveBg: "#cc2020",
    tabActiveText: "#ffffff",
    textPrimary: "#ffe8e8",
    textSecondary: "#cc7777",
    headerBg: "#0e0000",
    searchBg: "#240000",
    particles: "✊",
    particleCount: 8,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a0000,#cc2020,#f9c025,#cc2020,#7a0000)",
      textColor: "#f9c025",
      subtextColor: "#ffcc55",
      emoji: "✊",
      line1: "Happy Labour Day! May 1st 🌐",
      line2: "Honouring the workers who build the world",
    },
    font: null,
  },

  childrens_day: {
    // Bright multicolour on sky-blue — playful & joyful
    accent: "#e07000",
    accentDark: "#b85800",
    bg: "#f0f8ff",
    cardBg: "#ffffff",
    cardBorder: "#a8d8f8",
    tabActiveBg: "#e07000",
    tabActiveText: "#ffffff",
    textPrimary: "#082040",
    textSecondary: "#3068a0",
    headerBg: "#ffffff",
    searchBg: "#e5f4ff",
    particles: "🎈",
    particleCount: 16,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0d47a1,#e07000,#e91e63,#e07000,#0d47a1)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.9)",
      emoji: "🎈",
      line1: "Happy Children's Day! 🎊",
      line2: "Celebrating the joy of childhood — for all",
    },
    font: null,
  },

  independence_day: {
    // Tricolour — saffron + white + green on deep navy
    accent: "#ff9500",
    accentDark: "#d47800",
    bg: "linear-gradient(160deg,#001a28 0%,#000e40 55%,#001a00 100%)",
    cardBg: "#001020",
    cardBorder: "#003060",
    tabActiveBg: "#ff9500",
    tabActiveText: "#001020",
    textPrimary: "#e0eeff",
    textSecondary: "#80a8cc",
    headerBg: "#000c1e",
    searchBg: "#001830",
    particles: "🇮🇳",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#005000,#ff9500,#ffffff28,#ff9500,#005000)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.88)",
      emoji: "🇮🇳",
      line1: "Happy Independence Day! Jai Hind 🎆",
      line2: "Proudly Indian — 78 years of freedom",
    },
    font: null,
  },

  republic_day: {
    accent: "#ff9500",
    accentDark: "#d47800",
    bg: "linear-gradient(160deg,#001a28 0%,#000e40 55%,#001a00 100%)",
    cardBg: "#001020",
    cardBorder: "#003060",
    tabActiveBg: "#ff9500",
    tabActiveText: "#001020",
    textPrimary: "#e0eeff",
    textSecondary: "#80a8cc",
    headerBg: "#000c1e",
    searchBg: "#001830",
    particles: "🇮🇳",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#005000,#ff9500,#ffffff28,#ff9500,#005000)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.88)",
      emoji: "🇮🇳",
      line1: "Happy Republic Day! Jai Hind 🎆",
      line2: "Honouring the Constitution of India — 26 January",
    },
    font: null,
  },

  pride: {
    // Rainbow spectrum — bold + joyful
    accent: "#e030c0",
    accentDark: "#b020a0",
    bg: "linear-gradient(150deg,#180015 0%,#0c0830 33%,#001810 66%,#180800 100%)",
    cardBg: "#100015",
    cardBorder: "#440060",
    tabActiveBg: "#e030c0",
    tabActiveText: "#ffffff",
    textPrimary: "#ffe8ff",
    textSecondary: "#cc88ee",
    headerBg: "#0e0012",
    searchBg: "#1c0020",
    particles: "🏳️‍🌈",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#e91e8c,#ff6000,#ffd700,#4caf50,#2196f3,#9c27b0)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.92)",
      emoji: "🏳️‍🌈",
      line1: "Happy Pride Month! 🌈",
      line2: "Love is love — celebrate with us",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  EAST ASIAN
  //  CNY       → imperial red + dragon gold on deep scarlet
  //  Lantern   → lantern red-crimson + amber on near-black
  //  Mid-Aut   → moon gold on ink-black
  //  Jpn NY    → ink-black + crane white + ume-red
  //  Sakura    → petal pink on pure white
  //  Golden Wk → rising-sun red + cream
  //  Tanabata  → star-indigo + silver on midnight
  //  Songkran  → water-blue on deep teal
  //  Chuseok   → harvest gold + pine on cream
  //  Seollal   → pojagi-red + ivory
  //  Dragon Bt → dragon-green + gold on teal-black
  //  Qixi      → stardust violet + pink on midnight
  // ══════════════════════════════════════════════════════════════════════

  chinese_new_year: {
    accent: "#d4a000",
    accentDark: "#a88000",
    bg: "linear-gradient(160deg,#1e0000 0%,#360000 55%,#1e0000 100%)",
    cardBg: "#220000",
    cardBorder: "#680000",
    tabActiveBg: "#d4a000",
    tabActiveText: "#220000",
    textPrimary: "#fff4e0",
    textSecondary: "#cc8844",
    headerBg: "#1c0000",
    searchBg: "#2c0000",
    particles: "🧧",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#cc0000,#ff3030,#d4a000,#ff3030,#cc0000)",
      textColor: "#d4a000",
      subtextColor: "#f0d060",
      emoji: "🐉",
      line1: "Xīn Nián Kuài Lè! 新年快乐 🧧",
      line2: "Wishing you prosperity, luck & joy",
    },
    font: null,
  },

  lantern_festival: {
    accent: "#e08000",
    accentDark: "#b86000",
    bg: "linear-gradient(160deg,#0c0008 0%,#180018 55%,#0c0008 100%)",
    cardBg: "#120010",
    cardBorder: "#400038",
    tabActiveBg: "#e08000",
    tabActiveText: "#120010",
    textPrimary: "#fff8e0",
    textSecondary: "#cca050",
    headerBg: "#0e000c",
    searchBg: "#1e0018",
    particles: "🏮",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#380000,#c04000,#e08000,#c04000,#380000)",
      textColor: "#f9e060",
      subtextColor: "#f0c040",
      emoji: "🏮",
      line1: "Happy Lantern Festival! 元宵节快乐",
      line2: "Riddles, tang yuan & glowing lanterns",
    },
    font: null,
  },

  mid_autumn: {
    // Moonrise gold on deep ink-black
    accent: "#e0a000",
    accentDark: "#b88000",
    bg: "linear-gradient(160deg,#040412 0%,#08081e 55%,#040412 100%)",
    cardBg: "#060618",
    cardBorder: "#201860",
    tabActiveBg: "#e0a000",
    tabActiveText: "#060618",
    textPrimary: "#f0ecff",
    textSecondary: "#8880cc",
    headerBg: "#050516",
    searchBg: "#0c0c28",
    particles: "🥮",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#060630,#101080,#e0a000,#101080,#060630)",
      textColor: "#e0a000",
      subtextColor: "#f0d060",
      emoji: "🌕",
      line1: "Happy Mid-Autumn Festival! 中秋节快乐",
      line2: "Share mooncakes & joy under the full moon",
    },
    font: null,
  },

  japanese_new_year: {
    // Ink-black + white + ume-red — wabi-sabi
    accent: "#c02020",
    accentDark: "#a01818",
    bg: "linear-gradient(160deg,#0c0c0c 0%,#1a1a1a 100%)",
    cardBg: "#141414",
    cardBorder: "#303030",
    tabActiveBg: "#c02020",
    tabActiveText: "#ffffff",
    textPrimary: "#f8f8f8",
    textSecondary: "#a0a0a0",
    headerBg: "#0e0e0e",
    searchBg: "#1c1c1c",
    particles: "⛩️",
    particleCount: 8,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#181818,#c02020,#ffffff22,#c02020,#181818)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.78)",
      emoji: "⛩️",
      line1: "Akemashite Omedetou! 明けましておめでとう 🎍",
      line2: "Wishing you peace, health & good fortune",
    },
    font: null,
  },

  sakura_season: {
    // Cherry-blossom pink + white — spring Japan
    accent: "#e0607a",
    accentDark: "#c04860",
    bg: "#fff8fa",
    cardBg: "#ffffff",
    cardBorder: "#ffc8d8",
    tabActiveBg: "#e0607a",
    tabActiveText: "#ffffff",
    textPrimary: "#480020",
    textSecondary: "#a84060",
    headerBg: "#ffffff",
    searchBg: "#fff0f5",
    particles: "🌸",
    particleCount: 20,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#c84068,#e0607a,#fce8ee,#e0607a,#c84068)",
      textColor: "#ffffff",
      subtextColor: "#fce8f0",
      emoji: "🌸",
      line1: "Sakura Season! Cherry blossoms in full bloom 🌸",
      line2: "Japan's most beautiful season — seasonal treats await",
    },
    font: null,
  },

  golden_week: {
    // Rising-sun red + cream — Japan's five-day holiday
    accent: "#c82020",
    accentDark: "#a01818",
    bg: "#fff9f0",
    cardBg: "#ffffff",
    cardBorder: "#ffd0a0",
    tabActiveBg: "#c82020",
    tabActiveText: "#ffffff",
    textPrimary: "#300000",
    textSecondary: "#884040",
    headerBg: "#ffffff",
    searchBg: "#fff5e8",
    particles: "🌸",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#8b0000,#c82020,#ffffff28,#c82020,#8b0000)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.85)",
      emoji: "🎏",
      line1: "Japan Golden Week! ゴールデンウィーク 🎏",
      line2: "Japan's most festive week — special treats",
    },
    font: null,
  },

  tanabata: {
    // Star-indigo + silver on midnight
    accent: "#8060ff",
    accentDark: "#6040e0",
    bg: "linear-gradient(160deg,#060216 0%,#0a0530 55%,#060216 100%)",
    cardBg: "#080320",
    cardBorder: "#201868",
    tabActiveBg: "#8060ff",
    tabActiveText: "#ffffff",
    textPrimary: "#e8e0ff",
    textSecondary: "#9888cc",
    headerBg: "#060218",
    searchBg: "#0e0828",
    particles: "⭐",
    particleCount: 20,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#140058,#5030c0,#8060ff,#5030c0,#140058)",
      textColor: "#e0d8ff",
      subtextColor: "#c0b8f0",
      emoji: "🎋",
      line1: "Happy Tanabata! 七夕 — Star Festival 🌟",
      line2: "Write your wishes — the stars will grant them",
    },
    font: null,
  },

  songkran: {
    // Water-blue + sky on deep ocean
    accent: "#0090d0",
    accentDark: "#0070a8",
    bg: "linear-gradient(160deg,#001830 0%,#002848 55%,#001830 100%)",
    cardBg: "#002030",
    cardBorder: "#005080",
    tabActiveBg: "#0090d0",
    tabActiveText: "#ffffff",
    textPrimary: "#d8f4ff",
    textSecondary: "#60a8c8",
    headerBg: "#001828",
    searchBg: "#002840",
    particles: "💦",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#015888,#0090d0,#80d8f8,#0090d0,#015888)",
      textColor: "#ffffff",
      subtextColor: "#c8eeff",
      emoji: "💦",
      line1: "Sawasdee Pi Mai! Happy Songkran 🎉",
      line2: "Thai New Year Water Festival — cool & celebrate",
    },
    font: null,
  },

  chuseok: {
    // Harvest gold + pine green on cream — Korean Chuseok
    accent: "#b08000",
    accentDark: "#887800", // changed to amber-gold
    bg: "#fffdf0",
    cardBg: "#ffffff",
    cardBorder: "#f0e0a0",
    tabActiveBg: "#b08000",
    tabActiveText: "#ffffff",
    textPrimary: "#2a1e00",
    textSecondary: "#6a5000",
    headerBg: "#ffffff",
    searchBg: "#fffce8",
    particles: "🌕",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2a7d32,#b08000,#2a7d32,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#fffce0",
      emoji: "🌕",
      line1: "Chuseok Chal Bonaeseyo! 추석 잘 보내세요 🎑",
      line2: "Korean Harvest Moon — celebrate with our treats",
    },
    font: null,
  },

  seollal: {
    // Pojagi-red + ivory — Korean New Year
    accent: "#c02020",
    accentDark: "#980f0f", // fixed from near-duplicate
    bg: "#fff8f5",
    cardBg: "#ffffff",
    cardBorder: "#ffc8b0",
    tabActiveBg: "#c02020",
    tabActiveText: "#ffffff",
    textPrimary: "#2e0800",
    textSecondary: "#884040",
    headerBg: "#ffffff",
    searchBg: "#fff2ee",
    particles: "🎎",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a0000,#c02020,#f9d040,#c02020,#7a0000)",
      textColor: "#ffffff",
      subtextColor: "#ffe8c0",
      emoji: "🎎",
      line1: "Seollal! 새해 복 많이 받으세요 🎊",
      line2: "Korean Lunar New Year — joy & blessings",
    },
    font: null,
  },

  dragon_boat: {
    // Dragon-green + festival gold on deep teal-black
    accent: "#009070",
    accentDark: "#007058",
    bg: "linear-gradient(160deg,#001814 0%,#002c20 55%,#001814 100%)",
    cardBg: "#002018",
    cardBorder: "#004838",
    tabActiveBg: "#009070",
    tabActiveText: "#ffffff",
    textPrimary: "#d8fff8",
    textSecondary: "#60b8a0",
    headerBg: "#001810",
    searchBg: "#002a20",
    particles: "🐉",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#004838,#009070,#d4a000,#009070,#004838)",
      textColor: "#d4e860",
      subtextColor: "#b0d840",
      emoji: "🐉",
      line1: "Happy Dragon Boat Festival! 端午节快乐",
      line2: "Zongzi, dragon races & tradition",
    },
    font: null,
  },

  qixi: {
    // Stardust violet + rose on midnight
    accent: "#cc40e0",
    accentDark: "#a820c0",
    bg: "linear-gradient(160deg,#080018 0%,#100030 55%,#080018 100%)",
    cardBg: "#0c0020",
    cardBorder: "#300068",
    tabActiveBg: "#cc40e0",
    tabActiveText: "#0c0020",
    textPrimary: "#f0e8ff",
    textSecondary: "#b080d8",
    headerBg: "#0a0018",
    searchBg: "#160028",
    particles: "⭐",
    particleCount: 18,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#140050,#5020a0,#cc40e0,#5020a0,#140050)",
      textColor: "#f0c8ff",
      subtextColor: "#d8a8f0",
      emoji: "💫",
      line1: "Happy Qixi Festival! 七夕节快乐",
      line2: "Chinese Valentine's Day — love under a starlit sky",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  JEWISH
  //  Hanukkah → Maccabean blue + gold on midnight
  //  Passover → seder-plate amber on warm cream
  //  Rosh H   → honey-gold + apple-red on white
  //  Yom Kip  → soft silver-slate (solemn/reflective)
  //  Purim    → masquerade jewel-tones on ivory
  //  Shavuot  → dairy-white + wheat-gold on spring green
  // ══════════════════════════════════════════════════════════════════════

  hanukkah: {
    accent: "#1060c8",
    accentDark: "#0a48a0",
    bg: "linear-gradient(160deg,#040a1e 0%,#081630 55%,#040a1e 100%)",
    cardBg: "#060e22",
    cardBorder: "#1c3870",
    tabActiveBg: "#1060c8",
    tabActiveText: "#ffffff",
    textPrimary: "#d8eaff",
    textSecondary: "#6888c8",
    headerBg: "#040818",
    searchBg: "#0c1428",
    particles: "🕎",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0a3080,#1060c8,#d4a800,#1060c8,#0a3080)",
      textColor: "#d4a800",
      subtextColor: "#f0d060",
      emoji: "🕎",
      line1: "Chag Sameach! Happy Hanukkah 🕯️",
      line2: "Eight nights of light — our special treats",
    },
    font: null,
  },

  passover: {
    accent: "#c07800",
    accentDark: "#9a6000",
    bg: "#fffcf0",
    cardBg: "#ffffff",
    cardBorder: "#f0e0a0",
    tabActiveBg: "#c07800",
    tabActiveText: "#ffffff",
    textPrimary: "#2a1800",
    textSecondary: "#7a4800",
    headerBg: "#ffffff",
    searchBg: "#fff8e5",
    particles: "🍷",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a4000,#c07800,#f0d060,#c07800,#7a4000)",
      textColor: "#ffffff",
      subtextColor: "#fffce0",
      emoji: "🍷",
      line1: "Chag Pesach Sameach! Happy Passover 🌿",
      line2: "Celebrating freedom — our special items",
    },
    font: null,
  },

  rosh_hashanah: {
    // Apple-red + honey-gold on crisp white
    accent: "#c03030",
    accentDark: "#9a2020",
    bg: "#fff8f5",
    cardBg: "#ffffff",
    cardBorder: "#ffc8c8",
    tabActiveBg: "#c03030",
    tabActiveText: "#ffffff",
    textPrimary: "#300808",
    textSecondary: "#885050",
    headerBg: "#ffffff",
    searchBg: "#fff0ee",
    particles: "🍎",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2e7d32,#c03030,#2e7d32,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#e8f8e8",
      emoji: "🍎",
      line1: "Shanah Tovah! שנה טובה 🍯",
      line2: "May your new year be as sweet as honey & apple",
    },
    font: null,
  },

  yom_kippur: {
    // Silver-slate + ivory — solemn, reflective
    accent: "#6878a0",
    accentDark: "#506088",
    bg: "linear-gradient(160deg,#0a0c10 0%,#121820 100%)",
    cardBg: "#101418",
    cardBorder: "#242c38",
    tabActiveBg: "#6878a0",
    tabActiveText: "#ffffff",
    textPrimary: "#d8e0ec",
    textSecondary: "#708098",
    headerBg: "#0c1014",
    searchBg: "#181e28",
    particles: null,
    particleCount: 0,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#121820,#242c38,#121820)",
      textColor: "#c8d0dc",
      subtextColor: "#90a0b0",
      emoji: "🕊️",
      line1: "Gmar Chatimah Tovah — Yom Kippur",
      line2: "The Day of Atonement — may you be sealed for good",
    },
    font: null,
  },

  purim: {
    // Masquerade jewel — royal purple + gold + red on ivory
    accent: "#9020b0",
    accentDark: "#701890",
    bg: "#faf5ff",
    cardBg: "#ffffff",
    cardBorder: "#ddb8f0",
    tabActiveBg: "#9020b0",
    tabActiveText: "#ffffff",
    textPrimary: "#280040",
    textSecondary: "#7030a0",
    headerBg: "#ffffff",
    searchBg: "#f5eaff",
    particles: "🎭",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#5a1880,#9020b0,#d070d0,#9020b0,#5a1880)",
      textColor: "#ffffff",
      subtextColor: "#f0d8ff",
      emoji: "🎭",
      line1: "Chag Purim Sameach! Happy Purim 🎉",
      line2: "Costumes, hamantaschen & celebration",
    },
    font: null,
  },

  shavuot: {
    // Dairy-white + wheat-gold on spring green
    accent: "#2a7d32",
    accentDark: "#1b5e20",
    bg: "#f5fff5",
    cardBg: "#ffffff",
    cardBorder: "#b0d8b0",
    tabActiveBg: "#2a7d32",
    tabActiveText: "#ffffff",
    textPrimary: "#0a2e10",
    textSecondary: "#3a7040",
    headerBg: "#ffffff",
    searchBg: "#ecf8ec",
    particles: "🌸",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2a7d32,#c8a200,#2a7d32,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#e8f8e8",
      emoji: "📜",
      line1: "Chag Shavuot Sameach! Happy Shavuot 🌸",
      line2: "Celebrating the Torah, harvest & community",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  AFRICAN / CARIBBEAN
  // ══════════════════════════════════════════════════════════════════════

  kwanzaa: {
    // Pan-African — red + black + green
    accent: "#c82020",
    accentDark: "#a01818",
    bg: "linear-gradient(160deg,#0a0000 0%,#001400 50%,#0a0000 100%)",
    cardBg: "#0e0000",
    cardBorder: "#340800",
    tabActiveBg: "#c82020",
    tabActiveText: "#ffffff",
    textPrimary: "#ffe0d8",
    textSecondary: "#cc7755",
    headerBg: "#0c0000",
    searchBg: "#1c0400",
    particles: "🕯️",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a0000,#c82020,#1b5e20,#c82020,#7a0000)",
      textColor: "#f9c025",
      subtextColor: "#f0d060",
      emoji: "🕯️",
      line1: "Joyous Kwanzaa! 🌍",
      line2: "Seven principles, seven candles — African heritage",
    },
    font: null,
  },

  carnival_rio: {
    // Samba gold + green + electric on night
    accent: "#e0a000",
    accentDark: "#b88000",
    bg: "linear-gradient(150deg,#160028 0%,#0a1800 33%,#160800 66%,#0a0028 100%)",
    cardBg: "#160020",
    cardBorder: "#4a0060",
    tabActiveBg: "#e0a000",
    tabActiveText: "#160020",
    textPrimary: "#fff8d0",
    textSecondary: "#cc8850",
    headerBg: "#100018",
    searchBg: "#200030",
    particles: "🎊",
    particleCount: 18,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#006600,#e0a000,#009c3b,#e0a000,#006600)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.9)",
      emoji: "🎊",
      line1: "Carnaval do Rio! Feliz Carnaval 🎉",
      line2: "The world's greatest party — samba & colour",
    },
    font: null,
  },

  carnival_caribbean: {
    // Tropical — turquoise + gold + sunshine on deep blue
    accent: "#e06800",
    accentDark: "#b85000",
    bg: "linear-gradient(160deg,#001830 0%,#002048 55%,#001830 100%)",
    cardBg: "#002038",
    cardBorder: "#004880",
    tabActiveBg: "#e06800",
    tabActiveText: "#002038",
    textPrimary: "#d8f4ff",
    textSecondary: "#60a8cc",
    headerBg: "#001828",
    searchBg: "#003050",
    particles: "🌴",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#e06800,#f9d040,#00bcd4,#f9d040,#e06800)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.9)",
      emoji: "🌴",
      line1: "Caribbean Carnival! 🎉",
      line2: "Steel drums, colour & culture",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  LATIN AMERICAN
  // ══════════════════════════════════════════════════════════════════════

  dia_de_muertos: {
    // Marigold orange + violet on near-black — ofrenda
    accent: "#e08000",
    accentDark: "#b86000",
    bg: "linear-gradient(160deg,#080010 0%,#100015 55%,#080010 100%)",
    cardBg: "#0c000e",
    cardBorder: "#400055",
    tabActiveBg: "#e08000",
    tabActiveText: "#0c000e",
    textPrimary: "#fff0d8",
    textSecondary: "#cc9060",
    headerBg: "#0a000c",
    searchBg: "#160014",
    particles: "🏵️",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#200038,#8800a0,#e08000,#8800a0,#200038)",
      textColor: "#e08000",
      subtextColor: "#f0c060",
      emoji: "🌼",
      line1: "¡Feliz Día de los Muertos! 🌼",
      line2: "Marigolds, altars & honouring loved ones",
    },
    font: null,
  },

  cinco_de_mayo: {
    // Mexican flag — eagle-red + emerald on cream
    accent: "#b81818",
    accentDark: "#900e0e",
    bg: "#f8fff8",
    cardBg: "#ffffff",
    cardBorder: "#a8d8a8",
    tabActiveBg: "#b81818",
    tabActiveText: "#ffffff",
    textPrimary: "#0a2a0a",
    textSecondary: "#2a6a2a",
    headerBg: "#ffffff",
    searchBg: "#edfaed",
    particles: "🎉",
    particleCount: 14,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#006400,#b81818,#f0f0f0,#b81818,#006400)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.9)",
      emoji: "🎉",
      line1: "¡Feliz Cinco de Mayo! 🇲🇽",
      line2: "Celebrating Mexican heritage, resilience & culture",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  EUROPEAN
  // ══════════════════════════════════════════════════════════════════════

  oktoberfest: {
    // Bavarian blue + wheat-gold on white — lederhosen & lager
    accent: "#1045a0",
    accentDark: "#0a3080",
    bg: "#f0f5ff",
    cardBg: "#ffffff",
    cardBorder: "#a0c0f0",
    tabActiveBg: "#1045a0",
    tabActiveText: "#ffffff",
    textPrimary: "#061838",
    textSecondary: "#2860a0",
    headerBg: "#ffffff",
    searchBg: "#e8f0ff",
    particles: "🍺",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0a3080,#1045a0,#c8a000,#1045a0,#0a3080)",
      textColor: "#ffffff",
      subtextColor: "#fff0b0",
      emoji: "🍺",
      line1: "Willkommen zum Oktoberfest! 🥨",
      line2: "Munich's world-famous festival — Prost!",
    },
    font: null,
  },

  bastille_day: {
    // Tricolour — bleu + rouge + blanc on deep navy
    accent: "#d02020",
    accentDark: "#a81818",
    bg: "linear-gradient(160deg,#040014 0%,#0a0030 55%,#040014 100%)",
    cardBg: "#080022",
    cardBorder: "#200068",
    tabActiveBg: "#d02020",
    tabActiveText: "#ffffff",
    textPrimary: "#e0e8ff",
    textSecondary: "#7088cc",
    headerBg: "#060018",
    searchBg: "#0e0030",
    particles: "🎆",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1a1a9c,#d02020,#ffffff28,#d02020,#1a1a9c)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.9)",
      emoji: "🗼",
      line1: "Joyeux 14 Juillet! Happy Bastille Day 🇫🇷",
      line2: "Liberté, Égalité, Fraternité — celebrating France",
    },
    font: null,
  },

  st_patricks_day: {
    // Shamrock green on white — Éire
    accent: "#1a7a28",
    accentDark: "#125e1e",
    bg: "#f0fff2",
    cardBg: "#ffffff",
    cardBorder: "#a0e0a8",
    tabActiveBg: "#1a7a28",
    tabActiveText: "#ffffff",
    textPrimary: "#082010",
    textSecondary: "#2a7038",
    headerBg: "#ffffff",
    searchBg: "#e8faea",
    particles: "🍀",
    particleCount: 16,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#145020,#1a7a28,#60c060,#1a7a28,#145020)",
      textColor: "#ffffff",
      subtextColor: "#d8f8d8",
      emoji: "🍀",
      line1: "Happy St. Patrick's Day! ☘️",
      line2: "The luck of the Irish — wearing green & celebrating",
    },
    font: null,
  },

  midsommar: {
    // Swedish midsummer — cornflower blue + birch-yellow + white
    accent: "#0060a0",
    accentDark: "#004880",
    bg: "#f8faff",
    cardBg: "#ffffff",
    cardBorder: "#a8c8f0",
    tabActiveBg: "#0060a0",
    tabActiveText: "#ffffff",
    textPrimary: "#081828",
    textSecondary: "#285888",
    headerBg: "#ffffff",
    searchBg: "#eef4ff",
    particles: "🌻",
    particleCount: 14,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#003060,#0060a0,#f9d040,#0060a0,#003060)",
      textColor: "#ffffff",
      subtextColor: "#c8e8ff",
      emoji: "🌻",
      line1: "Glad Midsommar! Happy Midsummer 🌸",
      line2: "Dancing, flowers & the midnight sun",
    },
    font: null,
  },

  burns_night: {
    // Tartan — Scotland's national colours: blue + white
    accent: "#0050a0",
    accentDark: "#003880",
    bg: "#f0f4ff",
    cardBg: "#ffffff",
    cardBorder: "#a0b8f0",
    tabActiveBg: "#0050a0",
    tabActiveText: "#ffffff",
    textPrimary: "#060e28",
    textSecondary: "#285090",
    headerBg: "#ffffff",
    searchBg: "#e8f0ff",
    particles: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    particleCount: 8,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#003060,#0050a0,#f0f0f0,#0050a0,#003060)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.85)",
      emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      line1: "Happy Burns Night! 25 January 🥃",
      line2: "Haggis, poetry & Scottish pride",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  SOUTH / SOUTHEAST ASIAN & OTHER
  // ══════════════════════════════════════════════════════════════════════

  vesak: {
    accent: "#c89000",
    accentDark: "#a07000",
    bg: "#fffdf0",
    cardBg: "#ffffff",
    cardBorder: "#f0e090",
    tabActiveBg: "#c89000",
    tabActiveText: "#ffffff",
    textPrimary: "#2a1e00",
    textSecondary: "#7a5000",
    headerBg: "#ffffff",
    searchBg: "#fffbe8",
    particles: "☸️",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2a7d32,#c89000,#2a7d32,#1b5e20)",
      textColor: "#ffffff",
      subtextColor: "#fffce0",
      emoji: "☸️",
      line1: "Happy Vesak / Buddha Purnima 🙏",
      line2: "Celebrating the Buddha's life & enlightenment",
    },
    font: null,
  },

  nowruz: {
    // Persian spring — leaf green + gold on white
    accent: "#2a8030",
    accentDark: "#1c6022",
    bg: "#f5fff5",
    cardBg: "#ffffff",
    cardBorder: "#a8d8a8",
    tabActiveBg: "#2a8030",
    tabActiveText: "#ffffff",
    textPrimary: "#0a2810",
    textSecondary: "#3a7040",
    headerBg: "#ffffff",
    searchBg: "#ecf8ec",
    particles: "🌱",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1b5e20,#2a8030,#c8a000,#ff6800,#2a8030)",
      textColor: "#ffffff",
      subtextColor: "#e8f8e8",
      emoji: "🌱",
      line1: "Nowruz Mubarak! نوروز مبارک 🌸",
      line2: "Persian New Year — welcoming spring",
    },
    font: null,
  },

  nauryz: {
    // Kazakh spring — nomadic sky blue + gold
    accent: "#0080a0",
    accentDark: "#006080",
    bg: "#f0faff",
    cardBg: "#ffffff",
    cardBorder: "#90d0f0",
    tabActiveBg: "#0080a0",
    tabActiveText: "#ffffff",
    textPrimary: "#012040",
    textSecondary: "#0860a0",
    headerBg: "#ffffff",
    searchBg: "#e5f5ff",
    particles: "🌺",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#005070,#0080a0,#c8a000,#0080a0,#005070)",
      textColor: "#ffffff",
      subtextColor: "#c8e8ff",
      emoji: "🌺",
      line1: "Наурыз Мейрамы! Happy Nauryz 🌿",
      line2: "Central Asian spring celebration",
    },
    font: null,
  },

  thaipusam: {
    // Temple gold + vermilion on ivory
    accent: "#d07000",
    accentDark: "#a85800",
    bg: "#fffcf0",
    cardBg: "#ffffff",
    cardBorder: "#ffe8a0",
    tabActiveBg: "#d07000",
    tabActiveText: "#ffffff",
    textPrimary: "#2e1800",
    textSecondary: "#7a4400",
    headerBg: "#ffffff",
    searchBg: "#fff9e5",
    particles: "🪷",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#7a3000,#d07000,#f9d040,#d07000,#7a3000)",
      textColor: "#ffffff",
      subtextColor: "#ffe8b0",
      emoji: "🪷",
      line1: "Happy Thaipusam! 🙏",
      line2: "Devotion to Lord Murugan — blessings to all",
    },
    font: null,
  },

  deepavali_sg: {
    // Same palette as Diwali — shared festival of light
    accent: "#f5a623",
    accentDark: "#d4881a",
    bg: "linear-gradient(160deg,#0d0400 0%,#1f0a00 45%,#090200 100%)",
    cardBg: "#1c0900",
    cardBorder: "#3d1c00",
    tabActiveBg: "#f5a623",
    tabActiveText: "#1c0900",
    textPrimary: "#fff8e1",
    textSecondary: "#c8a26a",
    headerBg: "#140600",
    searchBg: "#2a1200",
    particles: "🪔",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#2d1000,#5c2800,#2d1000)",
      textColor: "#ffd700",
      subtextColor: "#f5a623",
      emoji: "🪔",
      line1: "Happy Deepavali! 🪔",
      line2: "Singapore's Festival of Lights — celebrate with us",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  SPORTS
  //  IPL         → team-blue + gold on near-black (TV broadcast)
  //  ICC CWC     → grass-green + ICC-gold
  //  FIFA WC     → stadium-navy + trophy-gold
  //  UEFA Euros  → UEFA-blue + star-gold
  //  Olympics    → five-ring palette on ceremony-white
  //  NBA         → hardwood-orange on near-black
  //  Super Bowl  → gridiron-blue + Lombardi-gold
  //  Wimbledon   → grass-green + purple (traditional)
  //  Formula 1   → tarmac-black + racing-red + chrome
  //  ISL         → pitch-green + ISL-gold
  //  Pro Kabaddi → action-blue + raider-orange
  //  Chess       → board ivory + piece-ebony
  //  Commonwealth→ Commonwealth-blue + nations-gold
  // ══════════════════════════════════════════════════════════════════════

  ipl: {
    accent: "#0055e0",
    accentDark: "#0040b8",
    bg: "linear-gradient(160deg,#000535 0%,#000e55 55%,#000535 100%)",
    cardBg: "#000828",
    cardBorder: "#001880",
    tabActiveBg: "#0055e0",
    tabActiveText: "#ffffff",
    textPrimary: "#d8e5ff",
    textSecondary: "#6888cc",
    headerBg: "#000428",
    searchBg: "#000e40",
    particles: "🏏",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#000e55,#0055e0,#d4a800,#0055e0,#000e55)",
      textColor: "#d4a800",
      subtextColor: "#f0d060",
      emoji: "🏏",
      line1: "IPL Season is LIVE! 🏏",
      line2: "Match day energy — fuel your game",
    },
    font: null,
  },

  icc_cricket_world_cup: {
    accent: "#1a7a28",
    accentDark: "#125e1e",
    bg: "linear-gradient(160deg,#001800 0%,#002e00 55%,#001800 100%)",
    cardBg: "#001e00",
    cardBorder: "#005000",
    tabActiveBg: "#1a7a28",
    tabActiveText: "#ffffff",
    textPrimary: "#d8ffd8",
    textSecondary: "#68b868",
    headerBg: "#001400",
    searchBg: "#002800",
    particles: "🏆",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#005000,#1a7a28,#d4a800,#1a7a28,#005000)",
      textColor: "#d4a800",
      subtextColor: "#f0d060",
      emoji: "🏏",
      line1: "ICC Cricket World Cup! 🏆",
      line2: "The biggest stage in cricket — cheer & celebrate",
    },
    font: null,
  },

  fifa_world_cup: {
    // Stadium-navy + trophy-gold
    accent: "#c8a000",
    accentDark: "#a08000",
    bg: "linear-gradient(160deg,#041228 0%,#082048 55%,#041228 100%)",
    cardBg: "#060e20",
    cardBorder: "#142060",
    tabActiveBg: "#c8a000",
    tabActiveText: "#060e20",
    textPrimary: "#d8e5ff",
    textSecondary: "#6878c8",
    headerBg: "#040c1e",
    searchBg: "#0a1438",
    particles: "⚽",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0c2060,#c8a000,#0c2060)",
      textColor: "#c8a000",
      subtextColor: "#f0d060",
      emoji: "⚽",
      line1: "FIFA World Cup! The Beautiful Game 🏆",
      line2: "Every kick matters — fuel your football fever",
    },
    font: null,
  },

  uefa_euros: {
    accent: "#0055c8",
    accentDark: "#0040a0",
    bg: "linear-gradient(160deg,#040e2a 0%,#081840 55%,#040e2a 100%)",
    cardBg: "#060c20",
    cardBorder: "#101a58",
    tabActiveBg: "#0055c8",
    tabActiveText: "#ffffff",
    textPrimary: "#d8e5ff",
    textSecondary: "#6080cc",
    headerBg: "#040a1c",
    searchBg: "#08103a",
    particles: "⚽",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0c2060,#0055c8,#c8a000,#0055c8,#0c2060)",
      textColor: "#c8a000",
      subtextColor: "#f0d060",
      emoji: "🏆",
      line1: "UEFA Euros — Football's Finest! ⚽",
      line2: "Europe's best battle for the trophy",
    },
    font: null,
  },

  olympics: {
    // Ceremony white + five-ring primary blue + gold
    accent: "#c8a000",
    accentDark: "#a08000",
    bg: "linear-gradient(160deg,#040e28 0%,#081838 55%,#040e28 100%)",
    cardBg: "#060c20",
    cardBorder: "#101848",
    tabActiveBg: "#c8a000",
    tabActiveText: "#060c20",
    textPrimary: "#d8e5ff",
    textSecondary: "#6878c8",
    headerBg: "#040a1c",
    searchBg: "#080e30",
    particles: "🏅",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1060c8,#d02020,#c8a000,#1a7a28,#1060c8)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.9)",
      emoji: "🏅",
      line1: "The Olympics! Citius, Altius, Fortius 🏆",
      line2: "The world unites — celebrate every medal",
    },
    font: null,
  },

  nba_finals: {
    // Hardwood orange + chrome on near-black
    accent: "#e06000",
    accentDark: "#b84e00",
    bg: "linear-gradient(160deg,#0c0000 0%,#1e0000 100%)",
    cardBg: "#160000",
    cardBorder: "#480000",
    tabActiveBg: "#e06000",
    tabActiveText: "#160000",
    textPrimary: "#fff5e0",
    textSecondary: "#cc8844",
    headerBg: "#100000",
    searchBg: "#1e0000",
    particles: "🏀",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800000,#e06000,#c8a000,#e06000,#800000)",
      textColor: "#c8a000",
      subtextColor: "#f0d060",
      emoji: "🏀",
      line1: "NBA Finals! Who will be Champion? 🏆",
      line2: "The best in basketball — every play matters",
    },
    font: null,
  },

  super_bowl: {
    // Lombardi trophy gold + gridiron-blue on ceremony-dark
    accent: "#c8a000",
    accentDark: "#a08000",
    bg: "linear-gradient(160deg,#040e28 0%,#082040 55%,#040e28 100%)",
    cardBg: "#060c20",
    cardBorder: "#101a58",
    tabActiveBg: "#c8a000",
    tabActiveText: "#060c20",
    textPrimary: "#d8e5ff",
    textSecondary: "#6878c8",
    headerBg: "#040a1c",
    searchBg: "#08103a",
    particles: "🏈",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0c2060,#c8a000,#0c2060)",
      textColor: "#c8a000",
      subtextColor: "#f0d060",
      emoji: "🏈",
      line1: "Super Bowl Sunday! 🏈",
      line2: "The biggest game in American football — fuel up",
    },
    font: null,
  },

  wimbledon: {
    // All-England green + purple + white on white
    accent: "#5a1a8a",
    accentDark: "#401268",
    bg: "#f8fff8",
    cardBg: "#ffffff",
    cardBorder: "#a0e0a8",
    tabActiveBg: "#5a1a8a",
    tabActiveText: "#ffffff",
    textPrimary: "#0a1e08",
    textSecondary: "#408040",
    headerBg: "#ffffff",
    searchBg: "#edfaed",
    particles: "🎾",
    particleCount: 12,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#003060,#5a1a8a,#1a7a28,#5a1a8a,#003060)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.9)",
      emoji: "🎾",
      line1: "Wimbledon — The Championships 🏆",
      line2: "Strawberries, grass courts & tennis royalty",
    },
    font: null,
  },

  formula1: {
    // Tarmac-black + racing-red + chrome-silver
    accent: "#e02020",
    accentDark: "#b81818",
    bg: "linear-gradient(160deg,#0a0000 0%,#1a0000 55%,#0a0000 100%)",
    cardBg: "#120000",
    cardBorder: "#440000",
    tabActiveBg: "#e02020",
    tabActiveText: "#ffffff",
    textPrimary: "#ffe8e8",
    textSecondary: "#cc7777",
    headerBg: "#0c0000",
    searchBg: "#1e0000",
    particles: "🏎️",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800000,#e02020,#c0c0c0,#e02020,#800000)",
      textColor: "#ffffff",
      subtextColor: "#e0c0c0",
      emoji: "🏎️",
      line1: "Formula 1 Race Weekend! 🏁",
      line2: "Lights out and away we go — who takes pole?",
    },
    font: null,
  },

  isl_football: {
    accent: "#d09000",
    accentDark: "#a87000",
    bg: "linear-gradient(160deg,#001828 0%,#002040 55%,#001828 100%)",
    cardBg: "#002030",
    cardBorder: "#004870",
    tabActiveBg: "#d09000",
    tabActiveText: "#002030",
    textPrimary: "#d8f0ff",
    textSecondary: "#60a0c8",
    headerBg: "#001828",
    searchBg: "#003050",
    particles: "⚽",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#003060,#d09000,#003060)",
      textColor: "#d09000",
      subtextColor: "#f0d060",
      emoji: "⚽",
      line1: "ISL — Indian Super League is Back! ⚽",
      line2: "Indian football at its finest — eat, watch & cheer",
    },
    font: null,
  },

  pro_kabaddi: {
    // Action-blue + raider-orange
    accent: "#e07000",
    accentDark: "#b85800",
    bg: "linear-gradient(160deg,#001428 0%,#000e40 55%,#001428 100%)",
    cardBg: "#000e20",
    cardBorder: "#002860",
    tabActiveBg: "#e07000",
    tabActiveText: "#000e20",
    textPrimary: "#d8e8ff",
    textSecondary: "#6080c8",
    headerBg: "#000c1e",
    searchBg: "#001430",
    particles: "🤼",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#002868,#e07000,#002868)",
      textColor: "#e07000",
      subtextColor: "#f0d060",
      emoji: "🤼",
      line1: "Pro Kabaddi League! Can you raid? 💪",
      line2: "India's most thrilling sport — watch & dig in",
    },
    font: null,
  },

  chess_olympiad: {
    // Board ivory + piece-ebony
    accent: "#303030",
    accentDark: "#181818",
    bg: "#fafaf8",
    cardBg: "#ffffff",
    cardBorder: "#d8d8d0",
    tabActiveBg: "#303030",
    tabActiveText: "#ffffff",
    textPrimary: "#141414",
    textSecondary: "#606060",
    headerBg: "#ffffff",
    searchBg: "#f0f0e8",
    particles: "♟️",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#1a1a1a,#303030,#1a1a1a)",
      textColor: "#f0f0e8",
      subtextColor: "#c8c8c0",
      emoji: "♟️",
      line1: "Chess Olympiad! Battle of Minds 🧠",
      line2: "Nations compete — every move a masterpiece",
    },
    font: null,
  },

  commonwealth_games: {
    accent: "#0858c8",
    accentDark: "#044098",
    bg: "linear-gradient(160deg,#040e28 0%,#081838 55%,#040e28 100%)",
    cardBg: "#060c20",
    cardBorder: "#101848",
    tabActiveBg: "#0858c8",
    tabActiveText: "#ffffff",
    textPrimary: "#d8e5ff",
    textSecondary: "#6878c8",
    headerBg: "#040a1c",
    searchBg: "#080e30",
    particles: "🏅",
    particleCount: 10,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0c2060,#0858c8,#c8a000,#0858c8,#0c2060)",
      textColor: "#c8a000",
      subtextColor: "#f0d060",
      emoji: "🏅",
      line1: "Commonwealth Games! 🌏",
      line2: "54 nations, one spirit — celebrate every champion",
    },
    font: null,
  },

  // ══════════════════════════════════════════════════════════════════════
  //  SPECIAL EVENTS
  // ══════════════════════════════════════════════════════════════════════

  black_friday: {
    // Pure black + neon-red slash — urgency
    accent: "#e81010",
    accentDark: "#c00808",
    bg: "#080808",
    cardBg: "#111111",
    cardBorder: "#2a2a2a",
    tabActiveBg: "#e81010",
    tabActiveText: "#ffffff",
    textPrimary: "#f0f0f0",
    textSecondary: "#909090",
    headerBg: "#0a0a0a",
    searchBg: "#1a1a1a",
    particles: "🛍️",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0a0a0a,#e81010,#c8a000,#e81010,#0a0a0a)",
      textColor: "#c8a000",
      subtextColor: "#f0d060",
      emoji: "🔥",
      line1: "BLACK FRIDAY — Biggest Deals are HERE! 🔥",
      line2: "Massive savings — don't miss out",
    },
    font: null,
  },

  cyber_monday: {
    // Deep tech-navy + electric cyan
    accent: "#00c8e8",
    accentDark: "#00a0c0",
    bg: "linear-gradient(160deg,#020820 0%,#040e30 100%)",
    cardBg: "#040c20",
    cardBorder: "#0c2050",
    tabActiveBg: "#00c8e8",
    tabActiveText: "#040c20",
    textPrimary: "#d0f0ff",
    textSecondary: "#5898b8",
    headerBg: "#030a18",
    searchBg: "#080e28",
    particles: "💻",
    particleCount: 12,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#001840,#00c8e8,#001840)",
      textColor: "#00c8e8",
      subtextColor: "#80d8f0",
      emoji: "💻",
      line1: "CYBER MONDAY — Online Deals Unlocked! 💻",
      line2: "The best digital deals of the year",
    },
    font: null,
  },

  flash_sale: {
    // High-voltage red + amber lightning
    accent: "#e83000",
    accentDark: "#c02000",
    bg: "linear-gradient(160deg,#100000 0%,#1e0000 100%)",
    cardBg: "#160000",
    cardBorder: "#4a0000",
    tabActiveBg: "#e83000",
    tabActiveText: "#ffffff",
    textPrimary: "#ffe8e0",
    textSecondary: "#cc7060",
    headerBg: "#120000",
    searchBg: "#200000",
    particles: "⚡",
    particleCount: 16,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800000,#e83000,#c8a000,#e83000,#800000)",
      textColor: "#c8a000",
      subtextColor: "#f0d060",
      emoji: "⚡",
      line1: "⚡ FLASH SALE — Limited Time Only!",
      line2: "Prices slashed — grab yours before they're gone",
    },
    font: null,
  },

  grand_opening: {
    // Celebration gold + champagne on deep violet
    accent: "#d4a000",
    accentDark: "#a88000",
    bg: "linear-gradient(160deg,#0c0028 0%,#180050 55%,#0c0028 100%)",
    cardBg: "#100038",
    cardBorder: "#3a0080",
    tabActiveBg: "#d4a000",
    tabActiveText: "#100038",
    textPrimary: "#f5e8ff",
    textSecondary: "#a880d8",
    headerBg: "#0c0030",
    searchBg: "#1a0048",
    particles: "🎊",
    particleCount: 18,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#180050,#5020c0,#d4a000,#5020c0,#180050)",
      textColor: "#d4a000",
      subtextColor: "#f0d060",
      emoji: "🎊",
      line1: "Grand Opening! We're LIVE 🎉",
      line2: "Welcome — explore our full catalogue",
    },
    font: null,
  },

  anniversary: {
    // Champagne + rose gold on deep midnight
    accent: "#d08000",
    accentDark: "#a86000",
    bg: "linear-gradient(160deg,#0c0018 0%,#180030 55%,#0c0018 100%)",
    cardBg: "#100028",
    cardBorder: "#3a0068",
    tabActiveBg: "#d08000",
    tabActiveText: "#100028",
    textPrimary: "#f5e8ff",
    textSecondary: "#a878d8",
    headerBg: "#0c0020",
    searchBg: "#1a0038",
    particles: "🎂",
    particleCount: 14,
    themeClass: "theme-dark",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#800030,#d08000,#c8a000,#d08000,#800030)",
      textColor: "#c8a000",
      subtextColor: "#f0d060",
      emoji: "🎂",
      line1: "Celebrating Our Anniversary! 🎉",
      line2: "Thank you — special treats to mark the occasion",
    },
    font: null,
  },

  back_to_school: {
    // School-bus yellow + cobalt blue on crisp white
    accent: "#0850a8",
    accentDark: "#043880",
    bg: "#f5f8ff",
    cardBg: "#ffffff",
    cardBorder: "#a8c0f0",
    tabActiveBg: "#0850a8",
    tabActiveText: "#ffffff",
    textPrimary: "#060e28",
    textSecondary: "#284878",
    headerBg: "#ffffff",
    searchBg: "#e8f0ff",
    particles: "📚",
    particleCount: 10,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#072060,#0850a8,#f9c025,#0850a8,#072060)",
      textColor: "#ffffff",
      subtextColor: "#c8e0ff",
      emoji: "📚",
      line1: "Back to School Season! 📚",
      line2: "Fuel for busy students & teachers",
    },
    font: null,
  },

  summer_vibes: {
    // Sunshine yellow + ocean blue on sky
    accent: "#e09000",
    accentDark: "#b87000",
    bg: "#f0f8ff",
    cardBg: "#ffffff",
    cardBorder: "#a8d8f8",
    tabActiveBg: "#e09000",
    tabActiveText: "#ffffff",
    textPrimary: "#061828",
    textSecondary: "#3070a0",
    headerBg: "#ffffff",
    searchBg: "#e5f4ff",
    particles: "☀️",
    particleCount: 14,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#0d47a1,#e09000,#f9d040,#e09000,#0d47a1)",
      textColor: "#ffffff",
      subtextColor: "rgba(255,255,255,0.9)",
      emoji: "☀️",
      line1: "Summer Vibes! Beat the Heat ❄️",
      line2: "Cool treats for hot days — refresh yourself",
    },
    font: null,
  },

  monsoon: {
    // Rain-blue + petrichor-green on overcast white
    accent: "#0878c8",
    accentDark: "#055898",
    bg: "#f0f4f8",
    cardBg: "#ffffff",
    cardBorder: "#98c8e0",
    tabActiveBg: "#0878c8",
    tabActiveText: "#ffffff",
    textPrimary: "#081828",
    textSecondary: "#3870a0",
    headerBg: "#ffffff",
    searchBg: "#e5f0f8",
    particles: "🌧️",
    particleCount: 16,
    themeClass: "theme-light",
    banner: {
      show: true,
      bg: "linear-gradient(90deg,#015888,#0878c8,#88c8e8,#0878c8,#015888)",
      textColor: "#ffffff",
      subtextColor: "#c8e8ff",
      emoji: "🌧️",
      line1: "Monsoon Season! Chai & Snacks Weather ☕",
      line2: "Rainy days call for warm treats & comfort food",
    },
    font: null,
  },
};

export const getTheme = () => THEMES[ACTIVE_THEME] ?? THEMES.default;
